run_local:
	run/local.sh
run_summit:
	run/summit.sh
status_local:
	status/local.sh
status_summit:
	status/summit.sh
test_local:
	tests/local.sh
test_summit:
	tests/summit.sh
clean:
	rm -rf local summit *~ __pycache__ *.csv */*~



